package cardgen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"regexp"
	"strings"
	"time"
)

// CardConcept represents a single card concept generated by GPT-4o
type CardConcept struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"` // Used as DALL-E prompt
	Tags        []string `json:"tags"`
}

// ConceptGenerator generates diverse Dixit-style card concepts
type ConceptGenerator struct {
	apiKey string
	client *http.Client
}

// NewConceptGenerator creates a new concept generator
func NewConceptGenerator(apiKey string) *ConceptGenerator {
	return &ConceptGenerator{
		apiKey: apiKey,
		client: &http.Client{Timeout: 180 * time.Second}, // Long timeout for 100 concepts
	}
}

// GenerateConcepts uses GPT-4o to generate 100 diverse card concepts
// If theme is provided (non-empty, not "default"), cards will follow that theme
func (cg *ConceptGenerator) GenerateConcepts(ctx context.Context, theme string) ([]CardConcept, error) {
	// Build theme-specific instructions
	themeInstruction := ""
	if theme != "" && theme != "default" {
		themeInstruction = fmt.Sprintf(`
IMPORTANT THEME: All cards should follow the "%s" theme.
Interpret this theme creatively - it could mean:
- Visual style (e.g., "watercolor" = all watercolor art style)
- Subject matter (e.g., "ocean" = underwater scenes, sea creatures, nautical themes)
- Mood/atmosphere (e.g., "dark" = mysterious, shadowy, gothic imagery)
- Genre (e.g., "fantasy" = dragons, magic, mythical creatures, enchanted forests)
- Era/setting (e.g., "steampunk" = Victorian, clockwork, brass machinery)

Make sure every card fits the "%s" theme while maintaining diversity within that theme.
`, theme, theme)
	}

	prompt := fmt.Sprintf(`Generate 100 unique card concepts for the game Dixit.
%s
Dixit cards should be:
- Dreamlike, surreal, and imaginative
- Open to multiple interpretations
- Evocative of emotions, stories, or abstract ideas
- Family-friendly (no violence, gore, or mature themes)
- Original (no copyrighted characters, no famous landmarks, no real people)
- Without text, logos, or watermarks in the image

For each card, provide:
1. A short evocative title (2-4 words)
2. A detailed DALL-E prompt describing the scene, art style, mood, colors (under 400 chars). Always end with "No text, no watermarks, family-friendly illustration."
3. 3-5 thematic tags

Ensure diversity across:
- Themes: nature, fantasy, emotions, journeys, transformations, relationships, seasons, elements, dreams, memories
- Art styles: watercolor, oil painting, surrealism, impressionism, digital art, storybook illustration, fantasy art
- Moods: peaceful, mysterious, joyful, melancholic, whimsical, dramatic, serene, adventurous
- Color palettes: warm, cool, vibrant, muted, monochromatic, complementary

Return ONLY a valid JSON array with exactly 100 items. No markdown, no explanation, just the JSON:
[
  {
    "id": "card-001",
    "title": "Floating Library",
    "description": "A dreamy watercolor painting of ancient books floating in a starlit sky, their pages transforming into birds made of golden light. Soft purple and blue gradient background, magical atmosphere. No text, no watermarks, family-friendly illustration.",
    "tags": ["knowledge", "transformation", "night", "magic", "books"]
  }
]

Generate all 100 cards now.`, themeInstruction)

	log.Println("[CardGen] Sending request to GPT-4o (this may take 30-60 seconds)...")

	reqBody := map[string]interface{}{
		"model": "gpt-4o",
		"messages": []map[string]interface{}{
			{
				"role":    "system",
				"content": "You are a creative director for an art-driven storytelling game. Generate imaginative, evocative card concepts. Return only valid JSON, no markdown formatting.",
			},
			{
				"role":    "user",
				"content": prompt,
			},
		},
		"max_tokens":  16000,
		"temperature": 0.9,
	}

	jsonBody, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, "POST", "https://api.openai.com/v1/chat/completions", bytes.NewBuffer(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+cg.apiKey)

	resp, err := cg.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to send request: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	log.Printf("[CardGen] GPT-4o responded with status %d", resp.StatusCode)

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GPT-4o API error (%d): %s", resp.StatusCode, string(body))
	}

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
		Error *struct {
			Message string `json:"message"`
		} `json:"error"`
	}

	if err := json.Unmarshal(body, &result); err != nil {
		return nil, fmt.Errorf("failed to parse GPT-4o response: %w", err)
	}

	if result.Error != nil {
		return nil, fmt.Errorf("GPT-4o API error: %s", result.Error.Message)
	}

	if len(result.Choices) == 0 {
		return nil, fmt.Errorf("no choices in GPT-4o response")
	}

	// Clean and parse the JSON response
	content := cleanJSONResponse(result.Choices[0].Message.Content)

	var concepts []CardConcept
	if err := json.Unmarshal([]byte(content), &concepts); err != nil {
		return nil, fmt.Errorf("failed to parse concepts JSON: %w (content: %.500s...)", err, content)
	}

	// Validate and fix IDs to ensure they're sequential
	for i := range concepts {
		concepts[i].ID = fmt.Sprintf("card-%03d", i+1)
	}

	// Validate we got enough concepts
	if len(concepts) < TargetCardCount {
		return nil, fmt.Errorf("only generated %d concepts, need %d", len(concepts), TargetCardCount)
	}

	return concepts[:TargetCardCount], nil
}

// cleanJSONResponse strips markdown code blocks and extra whitespace from AI responses
func cleanJSONResponse(s string) string {
	// Remove markdown code blocks (```json ... ``` or ``` ... ```)
	re := regexp.MustCompile("(?s)```(?:json)?\\s*(.+?)\\s*```")
	if matches := re.FindStringSubmatch(s); len(matches) > 1 {
		s = matches[1]
	}

	// Trim whitespace
	s = strings.TrimSpace(s)

	return s
}
